spring:
  application:
    name: elearning-a01-m1
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: ${USERNAME}
    driver-class-name: org.postgresql.Driver
    password: ${PASSWORD}
    url: ${URL}
server:
  port: 8099