package co.istad.sengkim.elearninga01m1.features.course;

import co.istad.sengkim.elearninga01m1.features.category.Category;
import co.istad.sengkim.elearninga01m1.features.category.CategoryMapper;
import co.istad.sengkim.elearninga01m1.features.category.CategoryRepository;
import co.istad.sengkim.elearninga01m1.features.category.dto.CreateCategoryRequest;
import co.istad.sengkim.elearninga01m1.features.course.dto.CourseResponse;
import co.istad.sengkim.elearninga01m1.features.course.dto.CreateCourseRequest;
import co.istad.sengkim.elearninga01m1.features.instructor.InstructorProfile;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import java.time.LocalDateTime;

@Service
public class CourseServiceImpl implements CourseService{
    private final CourseRepository courseRepository;
    private final CategoryRepository categoryRepository;
    private final CourseMapper courseMapper;
    public CourseServiceImpl(CourseRepository courseRepository,CategoryRepository categoryRepository, CourseMapper courseMapper){
        this.courseRepository = courseRepository;
        this.categoryRepository = categoryRepository;
        this.courseMapper = courseMapper;
    }
    @Override
    public CourseResponse createCourse(Jwt jwt, CreateCourseRequest createCourseRequest) {
        if(courseRepository.existsBySlug(createCourseRequest.slug())){
            throw new ResponseStatusException(HttpStatus.CONFLICT,"Slug has been used.");
        }
        Category category = categoryRepository.findById(createCourseRequest.categoryId())
                .orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Category not found with this id."));
        //dto to domain ( dto -> dao )
        Course course = courseMapper.mapCreateCourseToCourse(createCourseRequest);
        //System data ( generated by system )
        course.setCategory(category);
        course.setCountRating(0);
        course.setCountRating(0);
        course.setIsDeleted(false);
        course.setIsPublished(false);
        course.setInstructorProfile(new InstructorProfile(jwt.getSubject()));
        course = courseRepository.save(course);
        return courseMapper.mapCourseToCourseResponse(course);
    }
}
